development:
  password: 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
  theme_id: 101874204836
  store: sienland.myshopify.com
  ignore_files:
  - settings_data.json
  - src
  - node_modules
  - package.json
  - package-lock.json
